# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db65bfd750da14ef3ea62e5ff58d8e9a35dfcded4402c8690c8ebf350d23b51e29b85caa42b78a2c34468bffbdd7636bff759c25abdf862936fa98f6e88924a9

test:
  secret_key_base: 1170e4118b6c2b371e21b4d95c961c85924ddc7985c096085c67ec3ecdc0b108900677d1b30e6521811c91ea3db2fa8d60d757a70b08c10f7579416969be8b95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
